GET http://localhost:5032/games

###

GET http://localhost:5032/games/1

###

POST http://localhost:5032/games
Content-Type: application/json

{
  "name": "Final Fantasy XIV",
  "genreId": 2,
  "price": 59.99,
  "releaseDate": "2010-09-30"
}

###

PUT http://localhost:5032/games/3
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genreId": 3,
  "price": 9.99,
  "releaseDate": "1992-02-01"
}

###

DELETE http://localhost:5032/games/2